function vec = autosimBuildSemanticFeatures(windObs, droneObs, tagObs, semantic, cfg)
    if autosimIsModuleEnabled(cfg, 'ontology_engine')
        try
            vec = autosim_ontology_engine('build_features', windObs, droneObs, tagObs, semantic, cfg);
            if isnumeric(vec)
                return;
            end
        catch
        end
    end

    vec = [ ...
        autosimNormalize01(windObs.wind_speed, 0.0, cfg.wind.speed_max), ...
        autosimNormalize01(autosimVizField(windObs, 'wind_velocity_mag', autosimWindVectorMag(autosimVizField(windObs, 'wind_velocity', windObs.wind_speed))), 0.0, cfg.wind.speed_max), ...
        autosimNormalize01(abs(autosimVizField(windObs, 'wind_acceleration_mag', autosimWindVectorMag(autosimVizField(windObs, 'wind_acceleration', 0.0)))), 0.0, max(1.0, cfg.ontology.gust_dvdt_high)), ...
        autosimWrapTo180(windObs.wind_direction) / 180.0, ...
        autosimNormalize01(abs(droneObs.roll), 0.0, deg2rad(cfg.thresholds.final_attitude_max_deg)*1.5), ...
        autosimNormalize01(abs(droneObs.pitch), 0.0, deg2rad(cfg.thresholds.final_attitude_max_deg)*1.5), ...
        autosimClampNaN(tagObs.u_norm, 0.0), ...
        autosimClampNaN(tagObs.v_norm, 0.0), ...
        autosimNormalize01(tagObs.jitter_px, 0.0, cfg.ontology.tag_jitter_unsafe_px), ...
        autosimClampNaN(tagObs.stability_score, 0.0), ...
        autosimClampNaN(semantic.wind_risk_enc, autosimEncodeCategory(semantic.wind_risk, {'low','medium','high'}, [0.0, 0.5, 1.0], 1.0)), ...
        autosimClampNaN(semantic.alignment_enc, autosimEncodeCategory(semantic.alignment_state, {'aligned','misaligned'}, [1.0, 0.0], 0.0)), ...
        autosimClampNaN(semantic.visual_enc, autosimEncodeCategory(semantic.visual_state, {'stable','unstable'}, [1.0, 0.0], 0.0)), ...
        autosimClampNaN(semantic.context_enc, autosimEncodeCategory(semantic.landing_context, {'safe','caution','unsafe'}, [1.0, 0.5, 0.0], 0.0)) ...
    ];
end


