function label = autosimNormalizeActionLabel(x)
    s = lower(strtrim(string(x)));
    label = repmat("Unknown", size(s));

    attemptMask = (s == "attemptlanding") | (s == "attempt_landing") | (s == "land") | ...
        (s == "landing") | (s == "safe") | (s == "stable") | (s == "safetoland") | ...
        (s == "attempt_landing_recommended") | (s == "clear_to_land") | ...
        (s == "proceed") | (s == "1") | (s == "true");

    holdMask = (s == "holdlanding") | (s == "hold_landing") | (s == "hold") | ...
        (s == "abort") | (s == "abortlanding") | (s == "delaylanding") | ...
        (s == "continuehover") | (s == "reapproach") | (s == "descend") | ...
        (s == "cancellanding") | (s == "goaround") | (s == "unsafe") | ...
        (s == "unstable") | (s == "unsafetoland") | (s == "stop") | ...
        (s == "hold_landing_recommended") | (s == "abort_recommended") | ...
        (s == "monitor_and_reassess") | (s == "0") | (s == "false");

    label(attemptMask) = "AttemptLanding";
    label(holdMask) = "HoldLanding";
end


