function autosimCleanupProcesses(cfg, launchPid)
    if nargin < 2
        launchPid = -1;
    end

    if isfinite(launchPid) && launchPid > 1
        autosimKillTree(launchPid);
    end

    cleanupScope = "global";
    if isfield(cfg, 'process') && isfield(cfg.process, 'cleanup_scope')
        cleanupScope = lower(string(cfg.process.cleanup_scope));
    end

    if cleanupScope == "instance"
        autosimRefreshRos2Daemon();
        pause(max(0.2, cfg.process.kill_settle_sec));
        return;
    end

    preSnap = autosimGetActiveProcessSnapshot();
    if strlength(strtrim(preSnap)) > 0
        fprintf('[AUTOSIM] Cleanup pre-snapshot:\n%s\n', preSnap);
    end

    for pass = 1:3
        system(['bash -i -c "set +m; ' ...
            'pgrep -f \"[r]os2 launch sjtu_drone_bringup sjtu_drone_bringup.launch.py\" | xargs -r kill -9 || true; ' ...
            'pkill -9 -f \"[r]os2 launch sjtu_drone_bringup\" || true; ' ...
            'pkill -9 -f \"[s]jtu_drone_bringup.launch.py\" || true; ' ...
            'pkill -9 -f \"[c]omponent_container\" || true; ' ...
            'pkill -9 -f \"[a]priltag\" || true; ' ...
            'pkill -9 -f \"[s]tatic_transform_publisher\" || true; ' ...
            'pkill -9 -f \"[r]obot_state_publisher\" || true; ' ...
            'pkill -9 -f \"[j]oint_state_publisher\" || true; ' ...
            'pkill -9 -f \"[s]pawn_drone\" || true; ' ...
            'pkill -9 -f \"[t]eleop_joystick\" || true; ' ...
            'pkill -9 -f \"[t]eleop_node\" || true; ' ...
            'pkill -9 -f \"[s]jtu_drone_control.*teleop\" || true; ' ...
            'pkill -9 -f \"[j]oy_node\" || true; ' ...
            'pkill -9 -f \"[g]azebo_wind_plugin_node\" || true; ' ...
            'pkill -9 gzserver || true; ' ...
            'pkill -9 gzclient || true; ' ...
            'pkill -9 -x joy_node || true; ' ...
            'pkill -9 -x teleop_node || true; ' ...
            'pkill -9 -x static_transform_publisher || true; ' ...
            'pkill -9 -x robot_state_publisher || true; ' ...
            'pkill -9 -x joint_state_publisher || true; ' ...
            'pkill -9 -x rviz2 || true; ' ...
            'pkill -9 -f \"[r]viz2\" || true" 2>/dev/null']);
        pause(0.25 * pass);
    end

    autosimKillActiveProcessTrees();
    autosimRefreshRos2Daemon();

    verifyTimeout = 8.0;
    if isfield(cfg, 'process') && isfield(cfg.process, 'cleanup_verify_timeout_sec') && isfinite(cfg.process.cleanup_verify_timeout_sec)
        verifyTimeout = max(1.0, cfg.process.cleanup_verify_timeout_sec);
    end
    autosimWaitForProcessCleanup(verifyTimeout);

    % Final hard pass for frequent duplicate-node offenders.
    system(['bash -i -c "set +m; ' ...
        'pkill -9 -x joy_node || true; ' ...
        'pkill -9 -x teleop_node || true; ' ...
        'pkill -9 -x static_transform_publisher || true; ' ...
        'pkill -9 -x robot_state_publisher || true; ' ...
        'pkill -9 -x joint_state_publisher || true; ' ...
        'pkill -9 -x rviz2 || true" 2>/dev/null']);
    autosimWaitForProcessCleanup(2.0);

    postSnap = autosimGetActiveProcessSnapshot();
    if strlength(strtrim(postSnap)) > 0
        fprintf('[AUTOSIM] Cleanup post-snapshot (still alive):\n%s\n', postSnap);
    end

    pause(max(0.2, cfg.process.kill_settle_sec));
end


