function autosimUpdateScenarioRealtimePlot(viz, state)
    persistent warnedRealtimeVizFailure

    if isempty(viz) || ~isfield(viz, 'fig') || ~isgraphics(viz.fig)
        return;
    end

    if nargin < 2 || isempty(state)
        return;
    end

    try

        sensors = struct();
        semantic = struct();
        semVec = nan(1, numel(viz.cfg.ontology.semantic_feature_names));
        if isfield(state, 'sensors') && isstruct(state.sensors)
            sensors = state.sensors;
        end
        if isfield(state, 'semantic') && isstruct(state.semantic)
            semantic = state.semantic;
        end
        if isfield(state, 'semVec') && ~isempty(state.semVec)
            semVec = double(state.semVec(:)).';
        end

        if isfield(viz, 'flowTitle') && isgraphics(viz.flowTitle)
            windSpeedNow = autosimVizField(sensors, 'windSpeed', nan);
            windDirNow = autosimVizField(sensors, 'windDirDeg', nan);
            if isfinite(windSpeedNow) && isfinite(windDirNow)
                set(viz.flowTitle, 'String', sprintf('Scenario %03d Ontology Flow (hover=%.2fm, wind=%.2f@%.1fdeg)', ...
                    autosimVizField(viz, 'scenarioId', 0), autosimVizField(viz, 'hoverHeightM', nan), windSpeedNow, windDirNow));
            else
                set(viz.flowTitle, 'String', sprintf('Scenario %03d Ontology Flow (hover=%.2fm)', ...
                    autosimVizField(viz, 'scenarioId', 0), autosimVizField(viz, 'hoverHeightM', nan)));
            end
        end

        sensorVals = [ ...
            autosimNormalize01(autosimVizField(sensors, 'windSpeed', nan), 0.0, viz.cfg.wind.speed_max), ...
            autosimNormalize01(abs(autosimVizField(sensors, 'rollDeg', nan)), 0.0, viz.cfg.thresholds.final_attitude_max_deg), ...
            autosimNormalize01(abs(autosimVizField(sensors, 'pitchDeg', nan)), 0.0, viz.cfg.thresholds.final_attitude_max_deg), ...
            autosimNormalize01(autosimVizField(sensors, 'altitude', nan), 0.0, max(viz.cfg.scenario.hover_height_max_m, 0.5)), ...
            autosimNormalize01(abs(autosimVizField(sensors, 'vz', nan)), 0.0, viz.cfg.agent.no_model_max_abs_vz), ...
            autosimNormalize01(autosimVizField(sensors, 'tagErr', nan), 0.0, viz.cfg.agent.no_model_max_tag_error), ...
            autosimNormalize01(autosimVizField(sensors, 'tagJitterPx', nan), 0.0, viz.cfg.ontology.tag_jitter_unsafe_px), ...
            autosimClampNaN(autosimVizField(sensors, 'tagStabilityScore', nan), 0.0) ...
        ];
        set(viz.sensorBar, 'YData', sensorVals);
        sensorStateLabels = {
            autosimVizLevelText(sensorVals(1), {'calm','breezy','windy'}), ...
            autosimVizLevelText(sensorVals(2), {'flat','tilted','aggressive'}), ...
            autosimVizLevelText(sensorVals(3), {'flat','tilted','aggressive'}), ...
            autosimVizLevelText(sensorVals(4), {'low','hover','high'}), ...
            autosimVizLevelText(sensorVals(5), {'steady','moving','fast'}), ...
            autosimVizLevelText(sensorVals(6), {'locked','offset','far'}), ...
            autosimVizLevelText(sensorVals(7), {'stable','noisy','chaotic'}), ...
            autosimVizLevelText(sensorVals(8), {'poor','usable','good'}) ...
        };
        for i = 1:numel(viz.sensorLabels)
            set(viz.sensorLabels(i), 'String', sensorStateLabels{i}, 'Position', [i, min(0.92, sensorVals(i) + 0.05), 0]);
        end

        windRiskScore = autosimVizSemScore(semVec, 11, semantic, 'wind_risk_enc', nan);
        alignScore = autosimVizSemScore(semVec, 12, semantic, 'alignment_enc', nan);
        visualScore = autosimVizSemScore(semVec, 13, semantic, 'visual_enc', nan);
        safetyScore = autosimClampNaN(double(autosimVizField(semantic, 'isSafeForLanding', nan)), nan);
        feasibilityScore = autosimVizField(state, 'landingFeasibility', autosimVizField(semantic, 'landing_feasibility', nan));
        conceptVals = [ ...
            autosimClampNaN(windRiskScore, 0.0), ...
            autosimClampNaN(alignScore, 0.0), ...
            autosimClampNaN(visualScore, 0.0), ...
            autosimClampNaN(safetyScore, 0.0), ...
            autosimClampNaN(feasibilityScore, 0.0) ...
        ];
        set(viz.conceptBar, 'YData', conceptVals);
        conceptStateLabels = {
            autosimVizCompactToken(string(autosimVizField(semantic, 'wind_pattern', autosimVizField(semantic, 'wind_risk', "unknown")))), ...
            autosimVizCompactToken(string(autosimVizField(semantic, 'alignment_trend', autosimVizField(semantic, 'alignment_state', "unknown")))), ...
            autosimVizCompactToken(string(autosimVizField(semantic, 'visual_pattern', autosimVizField(semantic, 'visual_state', "unknown")))), ...
            autosimVizCompactToken(string(autosimVizField(semantic, 'control_difficulty', autosimVizField(semantic, 'drone_state', "unknown")))), ...
            autosimVizLevelText(conceptVals(5), {'low','medium','high'}) ...
        };
        for i = 1:numel(viz.conceptLabels)
            set(viz.conceptLabels(i), 'String', conceptStateLabels{i}, 'Position', [i, min(0.92, conceptVals(i) + 0.05), 0]);
        end

        tSec = autosimVizField(state, 'tSec', nan);
        predStableProb = autosimVizField(state, 'predStableProb', nan);
        addpoints(viz.trendProb, tSec, predStableProb);
        addpoints(viz.trendFeas, tSec, feasibilityScore);
        addpoints(viz.trendCtx, tSec, safetyScore);

        if isfinite(tSec)
            xlim(viz.axTrend, [max(0, tSec - 25), max(25, tSec + 1)]);
        end

        predTxt = 'nan';
        if isfinite(predStableProb)
            predTxt = sprintf('%.2f', predStableProb);
        end

        sensorNodeScores = [ ...
            sensorVals(1), ...
            max(sensorVals(2), sensorVals(3)), ...
            autosimNanMean(sensorVals(6:8)), ...
            autosimNanMean(sensorVals(4:5)) ...
        ];
        conceptNodeScores = [ ...
            autosimClampNaN(windRiskScore, 0.0), ...
            autosimClampNaN(alignScore, 0.0), ...
            autosimClampNaN(visualScore, 0.0), ...
            autosimClampNaN(safetyScore, 0.0) ...
        ];
        resultNodeScores = [ ...
            max(conceptNodeScores), ...
            autosimClampNaN(feasibilityScore, 0.0), ...
            autosimClampNaN(predStableProb, 0.0) ...
        ];

        sensorNodeText = {
            sprintf('%.2f m/s', autosimVizField(sensors, 'windSpeed', nan)), ...
            sprintf('R%.0f P%.0f', autosimVizField(sensors, 'rollDeg', nan), autosimVizField(sensors, 'pitchDeg', nan)), ...
            sprintf('e %.2f', autosimVizField(sensors, 'tagErr', nan)), ...
            sprintf('z %.2f\nv %.2f', autosimVizField(sensors, 'altitude', nan), autosimVizField(sensors, 'vz', nan)) ...
        };
        conceptNodeText = {
            autosimVizCompactToken(string(autosimVizField(semantic, 'wind_pattern', autosimVizField(semantic, 'wind_risk', "unknown")))), ...
            autosimVizCompactToken(string(autosimVizField(semantic, 'alignment_trend', autosimVizField(semantic, 'alignment_state', "unknown")))), ...
            autosimVizCompactToken(string(autosimVizField(semantic, 'visual_pattern', autosimVizField(semantic, 'visual_state', "unknown")))), ...
            autosimVizCompactToken(string(autosimVizField(semantic, 'control_difficulty', autosimVizField(semantic, 'drone_state', "unknown")))) ...
        };
        resultNodeText = {
            autosimVizCompactToken(string(autosimVizField(semantic, 'final_decision', "unknown"))), ...
            autosimVizCompactToken(string(autosimVizField(semantic, 'wind_risk', "unknown"))), ...
            sprintf('%s\np=%s', string(autosimVizField(state, 'inferTxt', "NO-LAND")), predTxt) ...
        };

        decisionMode = string(autosimVizField(semantic, 'final_decision', "hold_landing"));
        [summaryColor, summaryTextStr] = autosimVizDecisionBadge(decisionMode, autosimVizField(state, 'inferTxt', "NO-LAND"), feasibilityScore, predTxt);
        set(viz.summaryBox, 'FaceColor', summaryColor, 'EdgeColor', 0.75 * summaryColor);
        set(viz.summaryText, 'String', summaryTextStr, 'Color', [0.08 0.08 0.10]);

        for i = 1:numel(viz.sensorNodes)
            cardColor = autosimVizNodeColor(sensorNodeScores(i), false);
            set(viz.sensorRects(i), 'FaceColor', cardColor, 'EdgeColor', autosimVizEdgeColor(sensorNodeScores(i)));
            set(viz.sensorNodes(i), 'String', sensorNodeText{i});
        end
        for i = 1:numel(viz.conceptNodes)
            invertRisk = (i == 1);
            cardColor = autosimVizNodeColor(conceptNodeScores(i), invertRisk);
            set(viz.conceptRects(i), 'FaceColor', cardColor, 'EdgeColor', autosimVizEdgeColor(conceptNodeScores(i)));
            set(viz.conceptNodes(i), 'String', conceptNodeText{i});
        end
        for i = 1:numel(viz.resultNodes)
            cardColor = autosimVizNodeColor(resultNodeScores(i), false);
            set(viz.resultRects(i), 'FaceColor', cardColor, 'EdgeColor', autosimVizEdgeColor(resultNodeScores(i)));
            set(viz.resultNodes(i), 'String', resultNodeText{i});
        end

        for i = 1:size(viz.sensorToConcept, 1)
            srcIdx = viz.sensorToConcept(i,1);
            dstIdx = viz.sensorToConcept(i,2);
            edgeScore = autosimClampNaN(0.5 * (sensorNodeScores(srcIdx) + conceptNodeScores(dstIdx)), 0.0);
            set(viz.arrowSensor(i), 'Color', autosimVizEdgeColor(edgeScore), 'LineWidth', 0.8 + 2.0 * edgeScore);
        end
        for i = 1:size(viz.conceptToResult, 1)
            srcIdx = viz.conceptToResult(i,1);
            dstIdx = viz.conceptToResult(i,2);
            edgeScore = autosimClampNaN(0.5 * (conceptNodeScores(srcIdx) + resultNodeScores(dstIdx)), 0.0);
            set(viz.arrowConcept(i), 'Color', autosimVizEdgeColor(edgeScore), 'LineWidth', 0.8 + 2.0 * edgeScore);
        end

        flowLines = [ ...
            string(sprintf('phase=%s | t=%.1fs', string(autosimVizField(state, 'phase', "unknown")), autosimVizField(state, 'tSec', nan))); ...
            string(sprintf('wind=%s | align=%s | vis=%s', ...
                autosimVizCompactToken(string(autosimVizField(semantic, 'wind_pattern', autosimVizField(semantic, 'environment_state', "unknown")))), ...
                autosimVizCompactToken(string(autosimVizField(semantic, 'alignment_trend', autosimVizField(semantic, 'alignment_state', "unknown")))), ...
                autosimVizCompactToken(string(autosimVizField(semantic, 'visual_pattern', autosimVizField(semantic, 'visual_state', "unknown")))))); ...
            string(sprintf('control=%s | ctx=%s | feas=%.2f', ...
                autosimVizCompactToken(string(autosimVizField(semantic, 'control_difficulty', autosimVizField(semantic, 'drone_state', "unknown")))), ...
                autosimVizCompactToken(string(autosimVizField(semantic, 'final_decision', "unknown"))), feasibilityScore)); ...
            string(sprintf('cmd=(%.2f, %.2f, %.2f) | cmd_rms=%.2f', ...
                autosimVizField(sensors, 'cmdX', nan), autosimVizField(sensors, 'cmdY', nan), ...
                autosimVizField(sensors, 'cmdZ', nan), autosimVizField(sensors, 'followerCmdRms', nan))); ...
            string(sprintf('followers ready pose/state/tag/fly: %d/%d/%d/%d of %d', ...
                round(autosimVizField(sensors, 'followerPoseReady', 0)), ...
                round(autosimVizField(sensors, 'followerStateReady', 0)), ...
                round(autosimVizField(sensors, 'followerTagDetected', 0)), ...
                round(autosimVizField(sensors, 'followerFlying', 0)), ...
                round(autosimVizField(sensors, 'followerExpected', 0)))) ...
        ];
        set(viz.flowText, 'String', cellstr(flowLines));

        drawnow limitrate nocallbacks;
    catch ME
        if isempty(warnedRealtimeVizFailure) || ~warnedRealtimeVizFailure
            warnedRealtimeVizFailure = true;
            warning('[AUTOSIM] Realtime ontology plot update skipped: %s', ME.message);
        end
    end
end


