function tbl = autosimSummaryTable(results)
    if isempty(results)
        tbl = table();
        return;
    end

    tbl = struct2table(results);
    wanted = {
        'scenario_id','label','success','failure_reason', ...
        'hover_height_cmd','landing_height_m', ...
        'wind_speed_cmd','wind_dir_cmd', ...
        'mean_wind_speed','max_wind_speed', ...
        'wind_velocity_x','wind_velocity_y','wind_velocity', ...
        'wind_acceleration_x','wind_acceleration_y','wind_acceleration', ...
        'mean_abs_roll_deg','mean_abs_pitch_deg', ...
        'mean_abs_vz','max_abs_vz', ...
        'mean_tag_error','max_tag_error', ...
        'final_altitude','final_abs_speed','final_abs_roll_deg','final_abs_pitch_deg','final_tag_error', ...
        'stability_std_z','stability_std_vz','stability_std_vz_osc','touchdown_accel_rms','contact_count', ...
        'mean_imu_ang_vel','max_imu_ang_vel','mean_imu_lin_acc','max_imu_lin_acc', ...
        'max_contact_force','arm_force_fl_mean','arm_force_fr_mean','arm_force_rl_mean','arm_force_rr_mean', ...
        'arm_force_fl_peak','arm_force_fr_peak','arm_force_rl_peak','arm_force_rr_peak','arm_force_peak_max','arm_force_imbalance', ...
        'impact_weight_n','impact_total_force_limit_n','impact_arm_imbalance_limit_n','impact_arm_peak_limit_n','contact_metrics_available', ...
        'final_state', ...
        'landing_cmd_time','pred_decision','executed_action','action_source','probe_episode','probe_reason','gt_safe_to_land','decision_outcome', ...
        'semantic_environment','semantic_drone_state','semantic_visual_state','semantic_landing_context', ...
        'semantic_relation','semantic_integration','landing_feasibility','scenario_policy','target_case', ...
        'launch_pid','launch_log','exception_message'
    };

    cols = intersect(wanted, tbl.Properties.VariableNames, 'stable');
    tbl = tbl(:, cols);
end


